#!/bin/bash 
# JAR Feb 2, 2017 - this script processes single UV-vis spectra from the SpectraMax into a comma-separated text file
# a backup of the original datafile will be copied to the "archived" directory, and the processed files will be copied to the "processed" directory
# UPDATE Feb 4, 2017 - the optional first argument specifies the file extention to process (default is txt)
[ ! -d archived ] && mkdir archived
[ ! -d processed ] && mkdir processed
if [ "$#" -gt 1 ]; then
  echo "ERROR: Too many arguments! usage: convert_specmax.sh fileextention (optional, txt is default)"
  exit 1
fi
if [ "$#" == 1 ]; then
  NFILES=$(ls *.$1 | wc -l)
  if [ $NFILES -eq 0 ]; then
    echo "there are no .$1 files to convert!"
    exit 1
  fi
  echo "your .$1 files will be converted!"
  echo " "
  for fname in *.$1
  do
    F=$(basename $fname .$1)
    mv $F.$1 $F.txt
  done
fi
for fname in *.txt
do
  echo $fname
  cp $fname archived/$fname
  NPOINTS=$(head -n 3 $fname | tail -n 1 | awk '{print $9}')
  echo $NPOINTS
  head -n $((NPOINTS + 4)) $fname | tail -n $NPOINTS | awk '{print $1 ",", $3}' > processed/$fname
  rm $fname
done
