#!/bin/bash
# JAR May 15, 2017 - this script removes header lines from text files
# a backup of the original files will be copied to the "archived" directory, and the processed files will be copied to the "processed" directory
# the first argument is the number of lines to strip, and the optional second argument specifies the file extention to process (default is txt)
#[ ! -d archived ] && mkdir archived
#[ ! -d processed ] && mkdir processed

mkdir splitfiles

HEAD=$(head -n 6 $1 | tail -n 1)

cp $1 $1.working
NLINES=$(wc -l $1 | awk '{print $1}')
tail -n $(($NLINES-7)) $1 > $1.working

nsplits=$(awk '/Missing/' $1.working | awk $'{print $3}' | wc -l)
for split in {1..4}
do
  spl=$(awk '/Missing/' $1 | head -n $split | tail -n 1 | awk $'{print $3}' | awk -F "." $'{print $1}')
  echo $HEAD > splitfiles/$1.$split
  echo $spl >> splits.temp
  head -n 1 $1.working | awk -F  "," $'{print $1}' > fline.temp
  ncopylines=$(($(head -n $split splits.temp | tail -n 1) - $(cat fline.temp)))
  head -n $ncopylines $1.working >> splitfiles/$1.$split
  tail -n +$(($ncopylines+2)) $1.working > $1.working.temp
  mv $1.working.temp $1.working
done
rm $1.working
rm *.temp

# for line in {1..30}
# do
#   MISS=$(head -n $line $1.working | tail -n 1 | awk '{print $1}')
#   awk '{if ($MISS == 'Missing')
#     echo 'YAY'
#   else
#     echo 'BOO'}'
# done
