install.packages("ggplot2")
install.packages("plyr")
install.packages("superheat")
install.packages("reshape2")
install.packages("xlsx")
install.packages("multcomp")
install.packages("outliers")
install.packages("readr")
install.packages("readxl")
install.packages("fitdistrplus")
install.packages("devtools")
devtools::install_github("ropensci/plotly")

source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite(c("flowPloidy","ggcyto","flowCore"))
biocLite("flowViz")
biocLite("cytofWorkflow")
